apiVersion: apps/v1
kind: Deployment
metadata:
  name: issues-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: issues-service
  template:
    metadata:
      labels:
        app: issues-service
    spec:
      containers:
      - name: issues-service-container
        image: mpansuja/cloud-computing-images:issues.0.2.0
        ports:
        - containerPort: 8095
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: cloud-computing-secret
                key: deductive-cider-407703-sa.json
          - name: PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: cloud-computing-secret
                key: project-id.json