apiVersion: apps/v1
kind: Deployment
metadata:
  name: issues-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: issues-service
  template:
    metadata:
      labels:
        app: issues-service
    spec:
      containers:
      - name: issues-service-container
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8095